r4@hughes:  bkuhn | 2008-01-13 21:42:40 -0500    * Added the variables MYSQL_TEST_DBROOT, MYSQL_TEST_DBROOT_PASSWORD, and      MYSQL_TEST_DBHOST, which are the MySQL settings to use when running      the tests.
     This required multiple changes in the tests directory, to make use of
     them, as well as allowing them via configure.ac
 
     Note that I somewhat punted on this issue about spaces appearing in
     the passwords.  I forbid it in configure.ac, since I couldn't make all
     the tests' shell scripts work perfectly correct if there were spaces
     in the password.


git-svn-id: http://svn.gna.org/svn/pokersource/trunk@3521 c4f34931-41c7-4605-b615-9bb9f479c57e

diff --git a/tests/run.in b/tests/run.in
--- a/tests/run.in
+++ b/tests/run.in
@@ -29,16 +29,17 @@ set -e
 
 echo "RUNNING: $*" 
 
-if ! mysql -u "root" -h "localhost" -e "show databases" >/dev/null 2>&1 ; then
-    echo 'skipped because mysql -u "root" -e -h "localhost" "show databases" fails"'
+. ${top_srcdir}/tests/setupMysqlVariables
+
+if ! $MYSQL_ROOT_CMD -e "show databases" >/dev/null 2>&1 ; then
+    echo "skipped because $MYSQL_ROOT_CMD -e \"show databases\" fails"
     exit 0
 fi
-
 #
 # User for currency test
 #
-echo "CREATE USER 'currency'@ '%' IDENTIFIED BY '********';" | mysql -u root -h localhost > /dev/null 2>&1 || true
-echo "GRANT ALL PRIVILEGES ON * . * TO 'currency'@ '%' IDENTIFIED BY '********'" | mysql -u root -h localhost > /dev/null 2>&1 || true
+echo "CREATE USER 'currency'@ '%' IDENTIFIED BY '********';" | $MYSQL_ROOT_CMD > /dev/null 2>&1 || true
+echo "GRANT ALL PRIVILEGES ON * . * TO 'currency'@ '%' IDENTIFIED BY '********'" | $MYSQL_ROOT_CMD > /dev/null 2>&1 || true
 
 : ${srcdir:=.}
 export srcdir
@@ -56,7 +57,9 @@ fi
 #
 # For some reason php5 is unhappy if TZ is not set.
 #
-export TZ=Europe/Paris
+if [ -z "$TZ" ]; then
+    export TZ=Europe/Paris
+fi
 
 DEFAULT_COVERAGE_FILES=$(echo ${top_srcdir}/poker{network,ui,client2d}/*.py) 
 : ${COVERAGE_FILES:=$DEFAULT_COVERAGE_FILES}
