Skip and succeed if mysql admin is not set to root no password.
git-svn-id: http://svn.gna.org/svn/pokersource/trunk@1298 c4f34931-41c7-4605-b615-9bb9f479c57e

diff --git a/tests/run.in b/tests/run.in
--- a/tests/run.in
+++ b/tests/run.in
@@ -26,6 +26,11 @@
 #
 set -e
 
+if ! mysql -u "root" -h "localhost" -e "show databases" >/dev/null 2>&1 ; then
+    echo 'skipped because mysql -u "root" -e -h "localhost" "show databases" fails"'
+    exit 0
+fi
+
 : ${srcdir:=.}
 export srcdir
 : ${top_srcdir:=..}
